### ISSUE TITLE
Swift 3.2/4 Support

### ISSUE THREAD

**Issue by Kalvin126** [GriffinSchneider/DRYUI#22]
Any plans to update to Swift 3.2/4?

**Comment by jaredegan** [comment]
@GriffinSchneider Let's do it! What's good, Kalvin?

**Comment by Kalvin126** [comment]
Everything is good! We are preparing to update to Swift 4/Xcode 9/iOS 11 over in our boat as we expect GM's to be posted in a week or so.

**Comment by Kalvin126** [comment]
PR for `Swift 4` support: https://github.com/GriffinSchneider/DRYUI/pull/23
